import Head from "next/head";
import Image from "next/image";
import Link from "next/link"
import styled from "@emotion/styled"
import emblem from "../../public/images/emblem.png"
import Widget from "./widget";




export default function Navbar() {

  const NavContainer = styled.div`
  width: 100%;
  height: 20vh;
  background: #000;
  color: gray;
  align-items: center;
  justify-content: space-between;
  display: flex;

  `;

  const NavLogo = styled.div`

  `;

  const NavLinks = styled.div`
  display: flex;
  margin: 10px;
  > a {
    margin: 20px;
  }:hover{
    color: #fff;
  }
  @media (max-width: 470px) {
   display:none ;
  }
  `;


  return (
    <>
    <Head>
        <title>EC.TECH Angola</title>
        <meta charset="UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavContainer>
        <NavLogo>
          <Image src={emblem}  width={100} height={100} alt="logo do site"/>
        </NavLogo>
        <NavLinks>

              <Link href="/home"><a>Home</a></Link>


              <Link href="/servicos"><a>Serviços</a></Link>


              <Link href="/about"><a>Sobre Nós</a></Link>



        </NavLinks>
      <Widget/>

      </NavContainer>
    </>
  )
}
